SELECT PRODUCT_CODE, SALES_AMOUNT*PRICE AS SALES
FROM
(SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS SALES_AMOUNT
FROM OFFLINE_SALE O
GROUP BY PRODUCT_ID) AS O
LEFT JOIN PRODUCT P 
ON P.PRODUCT_ID = O.PRODUCT_ID
GROUP BY PRODUCT_CODE
ORDER BY SALES DESC,PRODUCT_CODE
