SELECT I.REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES,I.ADDRESS, ROUND(AVG(R.REVIEW_SCORE),2) AS SCORE
FROM REST_REVIEW R
INNER JOIN REST_INFO I
ON I.REST_ID = R.REST_ID
WHERE I.ADDRESS LIKE '서울%'AND R.REVIEW_SCORE IS NOT NULL
GROUP BY I.REST_ID
ORDER BY SCORE DESC, I.FAVORITES DESC