-- 코드를 입력하세요
SELECT YEAR(sales_date) AS YEAR, MONTH(sales_date) AS MONTH, GENDER, COUNT(DISTINCT ONLINE_SALE.USER_ID) AS USERS
FROM USER_INFO
INNER JOIN ONLINE_SALE 
ON ONLINE_SALE.user_id = USER_INFO.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY YEAR(sales_date), MONTH(sales_date), GENDER
ORDER BY 1,2,3