WITH CTE AS (
    SELECT USER_ID
    FROM USER_INFO
    WHERE JOINED LIKE '2021%'
)

SELECT 
    YEAR(O.SALES_DATE) AS YEAR, 
    MONTH(O.SALES_DATE) AS MONTH, 
    COUNT(DISTINCT O.USER_ID) AS PURCHASED_USERS, 
    ROUND(COUNT(DISTINCT O.USER_ID) / (SELECT COUNT(*) FROM CTE), 1) AS PURCHASED_RATIO
FROM CTE C
JOIN ONLINE_SALE O ON C.USER_ID = O.USER_ID
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH;