-- 코드를 입력하세요

WITH RECURSIVE cte AS (
    SELECT 0 AS n
    UNION ALL
    SELECT n+1 FROM cte WHERE n < 23)

SELECT cte.n, IFNULL(COUNT,0) AS COUNT
FROM cte
LEFT JOIN
(SELECT HOUR(DATETIME) AS HOUR, COUNT(DISTINCT ANIMAL_ID) AS COUNT
FROM ANIMAL_OUTS
GROUP BY 1
ORDER BY 1) AS AC
ON cte.n = AC.HOUR