-- 코드를 입력하세요
SELECT WM.MEMBER_ID, WM.MEMBER_NAME, WM.GENDER, WM.DATE_OF_BIRTH
FROM
(
SELECT MEMBER_ID, MEMBER_NAME, GENDER, SUBSTR(DATE_OF_BIRTH, 1,10) AS `DATE_OF_BIRTH`, TLNO
FROM MEMBER_PROFILE
HAVING GENDER = 'W' AND SUBSTR(DATE_OF_BIRTH, 6,2)=03 AND TLNO
) AS WM;