WITH REVIEW_COUNT AS (
    SELECT MEMBER_ID, COUNT(*) AS REVIEW_COUNT
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    )

SELECT M.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE,'%Y-%m-%d')
FROM REST_REVIEW R
JOIN MEMBER_PROFILE M ON M.MEMBER_ID = R.MEMBER_ID
JOIN REVIEW_COUNT RC ON RC.MEMBER_ID = R.MEMBER_ID
WHERE RC.REVIEW_COUNT = (SELECT MAX(REVIEW_COUNT) FROM REVIEW_COUNT)
ORDER BY R.REVIEW_DATE, R.REVIEW_TEXT;

