-- 코드를 입력하세요
SELECT MONTH(start_date), CAR_ID, COUNT(CAR_ID) RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN
(SELECT CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE>=20220801 AND START_DATE<=20221031
GROUP BY CAR_ID
HAVING COUNT(CAR_ID)>=5)
AND START_DATE>=20220801 AND START_DATE<=20221031
GROUP BY MONTH(start_date), CAR_ID
HAVING RECORDS > 0
ORDER BY 1, 2 DESC