SELECT FI.ID, FNI.FISH_NAME, FI.LENGTH
FROM FISH_INFO FI
LEFT JOIN FISH_NAME_INFO FNI
ON FI.FISH_TYPE = FNI.FISH_TYPE
WHERE (FI.FISH_TYPE, FI.LENGTH) IN 
(SELECT FISH_TYPE, MAX(LENGTH) LENGTH
FROM FISH_INFO 
GROUP BY FISH_TYPE)