-- 코드를 작성해주세요
SELECT SCORE, G.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM 
(SELECT EMP_NO, SUM(SCORE) AS SCORE
FROM HR_GRADE
GROUP BY EMP_NO) AS G
LEFT JOIN HR_EMPLOYEES E
ON E.EMP_NO = G.EMP_NO
ORDER BY SCORE DESC
LIMIT 1
