SELECT USED_GOODS_BOARD.TITLE,USED_GOODS_BOARD.BOARD_ID,  USED_GOODS_REPLY.REPLY_ID, USED_GOODS_REPLY.WRITER_ID, USED_GOODS_REPLY.CONTENTS	, SUBSTR(USED_GOODS_REPLY.CREATED_DATE, 1,10) AS CREATED_DATE
FROM USED_GOODS_REPLY
LEFT JOIN USED_GOODS_BOARD
ON USED_GOODS_BOARD.BOARD_ID = USED_GOODS_REPLY.BOARD_ID
WHERE USED_GOODS_BOARD.CREATED_DATE < 20221101 AND USED_GOODS_BOARD.CREATED_DATE > 20220930
ORDER BY USED_GOODS_REPLY.CREATED_DATE , USED_GOODS_BOARD.TITLE 