-- 코드를 입력하세요
SELECT CONCAT('/home/grep/src/', U.BOARD_ID,'/', U.FILE_ID, U.FILE_NAME, U.FILE_EXT) AS FILE_PATH
FROM
(SELECT BOARD_ID
FROM USED_GOODS_BOARD
ORDER BY VIEWS DESC
LIMIT 1) AS H
INNER JOIN USED_GOODS_FILE U
ON U.BOARD_ID = H.BOARD_ID
ORDER BY U.FILE_ID DESC