-- 코드를 입력하세요
SELECT BOOK.CATEGORY, SUM(SALES) TOTAL_SALES
FROM BOOK_SALES
LEFT JOIN BOOK
ON BOOK.BOOK_ID = BOOK_SALES.BOOK_ID
WHERE YEAR(SALES_DATE)=2022 AND MONTH(SALES_DATE)=1
GROUP BY BOOK.CATEGORY
ORDER BY 1